testMode: property
testLimit: 50000
shrinkLimit: 5000
seqLen: 50
coverage: true
format: text
contractAddr: "0x00a329c0648769A73afAc7F9381E08FB43dBEA72"
deployer: "0x30000"
sender: ["0x10000", "0x20000"]
psender: "0x10000"
balanceAddr: "0x20000"
balanceContract: 100000000000000000

