version: '3.8'

services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8545"
      - "--networkId"
      - "1337"
      - "--chainId"
      - "1337"
      - "--gasLimit"
      - "10000000"
      - "--accounts"
      - "10"
      - "--defaultBalanceEther"
      - "1000"
      - "--deterministic"
    networks:
      - evm-network

networks:
  evm-network:
    driver: bridge

